baseURL: https://sarahmary-blog.netlify.app/
languageCode: de-DE
title: Sarah Marys blog

enableEmoji: true

languageCode: "de-DE"
defaultContentLanguage: "de"
defaultContentLanguageInSubdir: false

markup:
  goldmark:
    extensions:
      extras:
        superscript:
          enable: true
    parser:
      wrapStandAloneImageWithinParagraph: false
    renderer:
      unsafe: true

module:
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  # workspace: bs-theme.work
  hugoVersion:
    extended: true
    min: 0.110.0
  imports:
    - path: github.com/gethinode/hinode
      disable: false
