main:
  - name: "About me"
    pageRef: "/about/"
    weight: 10
    params:
      alias: true
  - name: "Blog"
    pageRef: "/blog/"
    weight: 20
    params:
      alias: true
  - name: "Photo gallery"
    pageRef: "/photos/"
    weight: 30
    params:
      alias: true
  - name: "Optical Illusions"
    pageRef: "/illusions/"
    weight: 40
  - parent: "Optical Illusions"
    name: "Hering illusion"
    pageRef: "/illusions/hering/"
    weight: 10
  - parent: "Optical Illusions"
    name: "Müller-Lyer illusion"
    pageRef: "/illusions/mueller-lyer/"
    weight: 20
  - parent: "Optical Illusions"
    name: "Checker shadow illusion"
    pageRef: "/illusions/chessboard/"
    weight: 30
  - name: "GitHub"
    url: "https://github.com/deining/sarahblog"
    weight: 50
